### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by kaimantsch** [amatsuda/html5_validators#10]
I get:

undefined method `auto_html5_validation' for #<Class:0x007f11bd92f6a0>

My guess is that you require some javascript file to be added to the manifest when not using //= require_tree .

**Comment by imgarylai** [comment]
Hi, 

As this is an html5 validators, it suppose don't need to require any javascript.

Do you include this to your model?
```
include ActiveModel::Validations
```

**Comment by amatsuda** [comment]
Fixed via #14. Could you try version 1.2.2?
