### ISSUE TITLE
Images are missing in the README

### ISSUE THREAD

**Issue by prakashmurthy** [amatsuda/html5_validators#13]
http://img.skitch.com/20110517-8sagqrkjnmkinapmcc5tduy2b8.jpg & http://img.skitch.com/20110516-n3jhu5m4gan8iy1j8er1qb7yfa.jpg - included in https://raw.githubusercontent.com/amatsuda/html5_validators/master/README.rdoc don't display.

**Comment by amatsuda** [comment]
@prakashmurthy Fixed them. Thanks!
