### ISSUE TITLE
Should support non ActiveRecord::Base classes

### ISSUE THREAD

**Issue by ludwigschubert** [amatsuda/html5_validators#6]
The class method `auto_html5_validation` is added to ActiveRecord::Base, when imho it should be in `ActiveModel::Model`. This would allow auto_html5_validation to work with objects that just include `ActiveModel::Model`. (Which is often done for custom form objects, etc.)

**Comment by ludwigschubert** [comment]
@amatsuda Thank you so much! :dancer:

**Comment by amatsuda** [comment]
@ludwigschubert Thank YOU for telling us about the issue! :dancers:
