### ISSUE TITLE
Highlight all fields that fail validation at the same time

### ISSUE THREAD

**Issue by basilgohar** [amatsuda/html5_validators#8]
It would be nice if, instead of a single field failing validation being highlighted, the user fixes that field, and then attempts to submit again and they get the next field that failed, that all fields that fail validation are highlighted at the same time.  This will provide a better user experience and less steps to get a proper input from the user.

**Comment by ashes999** [comment]
:+1:  I would also like to see this if possible.

**Comment by amatsuda** [comment]
This is not controllable in HTML level. Please ask the browser vendors or hack on your own browser.
